---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ruochenhua.
--- DateTime: 2018/5/20 下午12:05
---

local server_io = require("server_io")

local s = server_io.new()

while true do
    s:mainloop(0.05)
end