---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ruochenhua.
--- DateTime: 2018/8/4 上午10:39
---

local packmanager = {}

local function packmanager.pack(raw_string)
    return string.pack("<s2", raw_string)
end

local function packmanager.send(fd, pack_msg)

end

return packmanager