---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ruochenhua.
--- DateTime: 2018/5/20 下午12:03
---

local server_io = {}
server_io.__index = server_io
local lsocket = require "lsocket"

function server_io.new()
    local fd = assert(lsocket.bind("127.0.0.1", 8888))
    return setmetatable({fds = {fd}, host = fd}, server_io)
end

function server_io:mainloop(timeout)
    local rd, wt = lsocket.select(self.fds, self.fds, timeout)

    if rd then
        for _, fd in pairs(rd) do
            if fd == self.host then
                print("got fd", fd)
            end
        end
    end

    if wt then
        for _, fd in pairs(wt) do
            print("wt", fd)
        end
    end
end

return server_io