---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ruochenhua.
--- DateTime: 2018/5/20 下午2:30
---

local client_io = require("client_io")

local c = client_io.new()

while true do
    c:mainloop(0.05)
end